Add mapping between Special Term I/II to Semester 3/4
AY2223S1-CS2103-F14-1/tp pull request #77
Opened 2022-10-16 06:52 UTC by SeekSaveServe

This adds mapping between Special Terms and Semesters 3 and 4.

Closes #72

2022-10-16 17:21 UTC, shenyih0ng requested changes

2022-10-17 00:16 UTC, SeekSaveServe commented on src/main/java/nus/climods/ui/common/Pill.java
> +        if (text.equals("Semester 3")) {
thx! i've shifted it to createSemesterPill

2022-10-17 03:17 UTC, sarrrdin approved these changes
LGTM 👍 Thanks for adding the mappings @SeekSaveServe!

2022-10-17 15:52 UTC, shenyih0ng approved these changes

2022-10-17 15:53 UTC, merged